### ISSUE TITLE
Crashplan crashes with trying to select "Other" location during restore setup

### ISSUE THREAD

**Issue by johnmckinzie** [jlesage/docker-crashplan-pro#342]
I'm running this image on an Asustor AS6602T using the Portainer and the following Compose file (999 is admin user/group on NAS):

```
version: '3'
services:
  crashplan-pro:
    hostname: **************
    container_name: crashplan-pro
    image: jlesage/crashplan-pro
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - KEEP_APP_RUNNING=1
      - CRASHPLAN_SRV_MAX_MEM=3G
      - USER_ID=999
      - GROUP_ID=999
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - "/home/admin/crashplan/config:/config"
      - "/volume2/storage:/storage"
```

When I try and setup a restore and get to the **Restore File Options** pop-up, Crashplan crashes when I select **Other** from the **Save selected files to** dropdown list. Below of a video of the issue:

https://www.youtube.com/watch?v=7dNozloJSdI

**Comment by jlesage** [comment]
Thanks for reporting, I'm looking at this.

**Comment by johnmckinzie** [comment]
Thank you for the quick response @jlesage . I really appreciate this project and have donate to it previously. Appreciate the support.

**Comment by theRealKLH** [comment]
I was coming here just for this same. I got about 400GB I gotta pull down before it gets deleted next week. freaking 90 day window!

If it weren't for you @jlesage....

**Comment by jlesage** [comment]
This is fixed with the latest Docker image version.

**Comment by theRealKLH** [comment]
I'm still crashing. It does get further though. Before it would crash after hanging for a bit once selecting "other". Now it moves on to the directory selection screen, but crashes after double-clicking on the folder I want to restore into.

**Comment by johnmckinzie** [comment]
I'm seeing the same behavior as @theRealKLH. I'm getting farther now, but it crashes on the directory selection.

**Comment by jlesage** [comment]
Thanks for the feedback.  Another fix is coming...

**Comment by jvarrone** [comment]
Will this get updated automatically if I have Watchtower installed?Sent from my Galaxy
-------- Original message --------From: Jocelyn Le Sage ***@***.***> Date: 12/26/21  11:04 AM  (GMT-05:00) To: jlesage/docker-crashplan-pro ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [jlesage/docker-crashplan-pro] Crashplan crashes with trying to select "Other" location during restore setup (Issue #342) 
Reopened #342.

**Comment by jlesage** [comment]
Yes.

**Comment by jlesage** [comment]
Latest Docker image should be good now.

**Comment by johnmckinzie** [comment]
Appears to be working! Thank you so much @jlesage!
