### ISSUE TITLE
/config/config/tmp/ fills up everytime a new version of CrashPlan client is release

### ISSUE THREAD

**Issue by daximus522** [jlesage/docker-crashplan-pro#350]
I find out a new version of CrashPlan is released by getting notified my /var/lib/docker partition on the host has filled up.

/config/conf/tmp/ in crashplan container gets filled with all the failed download attempts (just cleared out 9gigs this morning)... 

it contains 100s of files of the format c42.<numericidentifier>.dl in that folder.  

Do I need to tweak some permission on my file system somewhere so that it won't keep trying to download the new file?

it creates them pretty quickly as well.. roughly 2-3 a second in my case.  Once I pull down the new image with the upgraded client this behavior will stop until new one is released.

```
/config/conf/tmp # ls -l
total 9392748
-rw-r--r--    1 app      users            0 Jan 19 12:58 c42.100034533315007242.dl
-rw-r--r--    1 app      users            0 Jan 19 12:56 c42.10011909400837729358.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.10046948172591617479.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.10067067983702707780.dl
-rw-r--r--    1 app      users            0 Jan 19 12:58 c42.10084072146264458843.dl
-rw-r--r--    1 app      users            0 Jan 19 12:59 c42.10091010541218614939.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.10099477955085488233.dl
-rw-r--r--    1 app      users            0 Jan 19 12:56 c42.10100353098297797145.dl
-rw-r--r--    1 app      users            0 Jan 19 12:59 c42.10130928977396770820.dl
-rw-r--r--    1 app      users            0 Jan 19 12:58 c42.10140653968781203228.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.10157223096817604940.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.1017728647585524028.dl
-rw-r--r--    1 app      users            0 Jan 19 12:59 c42.10274058976698418303.dl
-rw-r--r--    1 app      users            0 Jan 19 12:56 c42.10301893892028697344.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.10376289314989569700.dl
-rw-r--r--    1 app      users            0 Jan 19 12:59 c42.10415411117984152915.dl
-rw-r--r--    1 app      users    209742817 Jan 19 12:54 c42.1044160722125250236.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.10460506521865202257.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.10472804985064383537.dl
-rw-r--r--    1 app      users            0 Jan 19 12:58 c42.10525425167733307038.dl
-rw-r--r--    1 app      users            0 Jan 19 12:58 c42.10549708849135289138.dl
-rw-r--r--    1 app      users            0 Jan 19 13:00 c42.10557885387349878097.dl
-rw-r--r--    1 app      users            0 Jan 19 12:56 c42.10567667790753843498.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.10598452833291037265.dl
-rw-r--r--    1 app      users            0 Jan 19 12:56 c42.106058484522882131.dl
-rw-r--r--    1 app      users            0 Jan 19 12:59 c42.10629572427089015313.dl
-rw-r--r--    1 app      users            0 Jan 19 12:58 c42.10641644334732991048.dl
-rw-r--r--    1 app      users            0 Jan 19 12:58 c42.10669024610694220871.dl
-rw-r--r--    1 app      users            0 Jan 19 12:56 c42.1068731796798610093.dl
-rw-r--r--    1 app      users            0 Jan 19 12:58 c42.10691536007387619732.dl
-rw-r--r--    1 app      users            0 Jan 19 12:57 c42.10693622306176258344.dl
-rw-r--r--    1 app      users    209742817 Jan 19 12:55 c42.10701800666496175097.dl
```

**Comment by excalibr18** [comment]
Seeing the same behavior in the Docker container on my Synology, although it seems to download every 15 minutes instead of the OP's 2-3 seconds.

**Comment by SJLBoulder** [comment]
Hmmm.  I just checked docker\appdata\crashplan-pro\conf\tmp on my Synology.  conf\tmp only contains 4 files - all named:  c42.*.dl    They are timestamped 30 minutes apart starting at "2022-01-19 11:45" to "2022-01-19 13:15."  So, obviously is not a problem on my Synology.

**Comment by theRealKLH** [comment]
I also had 10gb of files (200M every 15 minutes beginning yesterday) on my Synology.

**Comment by Tek4** [comment]
**CONFIRMED.**

I found 34 GiB of `c42.*.dl` files. A new download every 15 minutes.

```
docker container exec crashplan-pro ls -lt /config/conf/tmp
total 35640072
-rw-r--r--    1 app      app      209742817 Jan 21 19:57 c42.12580293313160388707.dl
-rw-r--r--    1 app      app      209742817 Jan 21 19:37 c42.13946189431256022518.dl
-rw-r--r--    1 app      app      209742817 Jan 21 19:22 c42.120296281001130550.dl
-rw-r--r--    1 app      app      209742817 Jan 21 19:07 c42.14206040643177846202.dl
-rw-r--r--    1 app      app      209742817 Jan 21 18:52 c42.18165929816492718125.dl
-rw-r--r--    1 app      app      209742817 Jan 21 18:32 c42.1108601444248561847.dl
-rw-r--r--    1 app      app      209742817 Jan 21 18:17 c42.7936280995522326635.dl
-rw-r--r--    1 app      app      209742817 Jan 21 17:57 c42.5663719808675147507.dl
-rw-r--r--    1 app      app      209742817 Jan 21 17:42 c42.1570348590304214135.dl
-rw-r--r--    1 app      app      209742817 Jan 21 17:27 c42.17473428746789910232.dl
[...]
```

**Comment by jlesage** [comment]
This issue has been also discussed in https://github.com/jlesage/docker-crashplan-pro/issues/336.

Not allowing writing to this `tmp` folder doesn't work, since this prevent the engine from starting.

But I finally found a way to prevent these downloads.  A new docker image with the fix should be available today, along with the update to CrashPlan version 8.8.2.

**Comment by jlesage** [comment]
This should now be fixed in the new image.

**Comment by bradtchapman** [comment]
Hi @jlesage.  I didn't see this issue before opening another one.  I have client version 8.8.2 and this is still happening - the downloads were coming in every 15 minutes.  

I'll try updating my image and check again...

**Comment by JeroenAdam** [comment]
This is still an issue. Currently using container jlesage/crashplan-pro:v2.16.4

**Comment by jlesage** [comment]
This is expected since you are using an outdated Docker image.
Please update your container with the latest Docker image.

**Comment by JeroenAdam** [comment]
But do you understand my position? Without petting/caring for my Docker server (running multiple services), the whole server stops working shortly after Crashplan releases a new version.

**Comment by halteach** [comment]
> Yes I agree this is a good workaround when running a version with the bug.
> 
> But note that if you don't keep your container's image up-to-date, CrashPlan will eventually stop to backup your files. CrashPlan requires to be at the latest version.
> 
> Maybe you should have a look at Watchtower: https://github.com/containrrr/watchtower This great piece of software automatically updates your Docker containers, without any user intervention.

will this update from the crashpan download or does it check for when you, jlesage,  have issued a new version?

**Comment by jlesage** [comment]
Watchtower checks for new Docker image versions.  So yes, it's when I publish a new Docker image that Watchtower will do its job.

**Comment by JeroenAdam** [comment]
> will this update from the crashpan download or does it check for when you, jlesage, have issued a new version?

That's what Watchtower does (as proposed by jlesageà).
It will check continuously for a new container version, if found, pull the image, stop the running container, delete it, run a new container with the same parameters as the previous one.

**Comment by JeroenAdam** [comment]
But what will happen if Crashplan releases a new version right after jlesage went on holidays? :)

**Comment by cgbale** [comment]
The latest docker image has a fix that blocks Crashplan from downloading new versions and filling up your partition. It’s a Crashplan bug but this latest docker image implemented a workaround for it. But you will still need to update to new docker images when new versions of crashplan are released.
